export const CREATE_GAME = 'CREATE_GAME'
export const WATCH_GAME = 'WATCH_GAME'
export const JOIN_GAME = 'JOIN_GAME'
export const LOAD_GAMES = 'LOAD_GAMES'
export const LOAD_MY_GAMES = 'LOAD_MY_GAMES'
export const PLAY_MOVE = 'PLAY_MOVE'
export const REVEAL_MOVES = 'REVEAL_MOVES'
export const REVEAL_BOARD = 'REVEAL_BOARD'
